#!/bin/sh

## -------------------------------------------------------------------
##
## Copyright (c) 2018 HashiCorp. All Rights Reserved.
##
## This file is provided to you under the Mozilla Public License
## Version 2.0 (the "License"); you may not use this file
## except in compliance with the License.  You may obtain
## a copy of the License at
##
##   https://www.mozilla.org/en-US/MPL/2.0/
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
## -------------------------------------------------------------------

tfe_show_description () (
    echo "Shows terraform active runs"
)

tfe_show_help () (
# Be sure to include the common options with tfe_usage_args
cat << EOF
SYNOPSIS
 tfe runs show

DESCRIPTION
 Shows all active runs in the Terraform Enterprise installation.

OPTIONS
$(tfe_usage_args)

NOTES
 The curl and jq commands are required.

 Only runs in state applying, planning and policy_checking are listed.
EOF
)

tfe_show () (
    # Ensure that tfe_token and tfe_address are set
    if ! check_required tfe_token tfe_address; then
        return 1
    fi

    echodebug "[DEBUG] API request to list active (applying, planning, policy_checking) runs:"
    url="$tfe_address/api/v2/admin/runs?filter%5Bstatus%5D=applying%2Cplanning%2Cpolicy_checking&include=workspace%2Cworkspace.organization"
    if ! list_resp="$(tfe_api_call "$url")"; then
        echoerr "Error listing active runs on $tfe_address"
        return 1
    fi

    listing="$(printf "%s" "$list_resp" |
        jq -r '.data[] | .id + " " + .attributes.status + " " + .attributes."created-at"')"
    echo "$listing"
)
